export const dummySkills: SkillRecord[] = [
  {
    id: "1",
    title: "Web Search",
    slug: "web-search",
    description: "Query the web and return structured results. Supports DuckDuckGo and Brave Search backends.",
    category: "Retrieval",
    tags: ["search", "retrieval", "web"],
    installCommand: "npx skild add web-search",
    createdAt: "2024-01-15",
    authorClerkId: "user_abc123",
    authorEmail: "jane@example.com",
  },
  {
    id: "2",
    title: "Code Executor",
    slug: "code-executor",
    description: "Run sandboxed Python or JavaScript snippets and return stdout, stderr, and exit code.",
    category: "Execution",
    tags: ["code", "sandbox", "execution"],
    installCommand: "npx skild add code-executor",
    createdAt: "2024-02-10",
    authorClerkId: "user_def456",
    authorEmail: "john@example.com",
  },
  {
    id: "3",
    title: "Memory Store",
    slug: "memory-store",
    description: "Persist and retrieve agent memory across sessions using vector embeddings.",
    category: "Memory",
    tags: ["memory", "vector", "embeddings"],
    installCommand: "npx skild add memory-store",
    createdAt: "2024-03-05",
    authorClerkId: "user_ghi789",
    authorEmail: "sara@example.com",
  },
  {
    id: "4",
    title: "File Reader",
    slug: "file-reader",
    description: "Read and parse PDF, DOCX, CSV, and plain text files into agent-consumable chunks.",
    category: "I/O",
    tags: ["files", "parsing", "documents"],
    installCommand: "npx skild add file-reader",
    createdAt: "2024-03-20",
    authorClerkId: "user_jkl012",
    authorEmail: "mike@example.com",
  },
  {
    id: "5",
    title: "Browser Operator",
    slug: "browser-operator",
    description: "Control a headless browser to navigate, click, and extract data from web pages.",
    category: "Automation",
    tags: ["browser", "scraping", "automation"],
    installCommand: "npx skild add browser-operator",
    createdAt: null,
    authorClerkId: "user_mno345",
    authorEmail: "lisa@example.com",
  },
];
