# query QueryName ($VariableName : VariableType = DefaultVariableValue) #* add auth level @auth({ level : PUBLIC , insecureReason : "Reason for public access" }) *#
# * {
# tableName(
#  where{
# * {fieldName : {contains : $VariableName}} *#
# } ,
# * orderBy:{fieldName:DESC} *#
# * limit:$VariableName
# )
# ? the resource of response
# {
#*  resourceField1  resourceField2  resourceField3
#* joinTableKey   {joinTableField1  joinTableField2  joinTableField3}
# }
#* }
query GetSkills($searchTerm: String = "" , $limit: Int = 10) @auth(level: PUBLIC, insecureReason: "Reason for public access"){
    skills(
        where:{
            _or:[
                {title : {contains : $searchTerm}},
                {description : {contains : $searchTerm}}
            ]
        }
        ,orderBy:{createdAt:DESC}
        ,limit:$limit
        
    ){
        id  title  description  tags  createdAt installCommand
        author {username imageUrl clerkId email}
    }
}
    
