# This is a file for you to write an un-named mutation. 
# Only one un-named mutation is allowed per file.
mutation {
  user_insert(data: {clerkId: "user_3Fu4wK23vP0AmeUb237IZKsIRIl", email: "mohamedgbr20233@gmail.com", imageUrl: "https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2ltYWdlcy5jbGVyay5kZXYvb2F1dGhfZ29vZ2xlL2ltZ18zRnU0d041WEdvVDRKSGhKeFB4dHEya0VGM1QifQ", username: "Mohamed Gbr"})
}